Feat/10.4/create logic for update vet info
IT-Academy-Social-Projects-KRV/Vet-Project pull request #88
Opened 2022-02-04 22:42 UTC by KobzarMax

2022-02-04 23:24 UTC, sanderpa requested changes

2022-02-04 23:24 UTC, sanderpa commented on client/src/app/admin-page/components/admin-edit-vet/admin-edit-vet.component.html
> +            <th mat-header-cell *matHeaderCellDef>No.</th>
It must be ID in this place

2022-02-04 23:24 UTC, sanderpa commented on client/src/app/admin-page/components/admin-edit-vet/admin-edit-vet.component.html
> +            <th mat-header-cell *matHeaderCellDef>Адреса</th>
missing mat-sort-header atribute

2022-02-04 23:24 UTC, sanderpa commented on client/src/app/admin-page/components/admin-edit-vet/admin-edit-vet.component.html
> +      <mat-paginator [pageSizeOptions]="[5, 10, 20, 50]" aria-label="Select page of users"></mat-paginator>
replace start pagination of 10 elements

2022-02-04 23:24 UTC, sanderpa commented on client/src/app/admin-page/components/admin-edit-pet/admin-edit-pet.component.ts
> +	onEdit() {}
what means this empty method?

2022-02-04 23:24 UTC, sanderpa commented on client/src/app/admin-page/components/admin-edit-vet/admin-edit-vet.component.ts
> +	getVets() {
Access modifiers need to be added

2022-02-04 23:24 UTC, sanderpa commented on client/src/app/admin-page/components/admin-edit-vet/admin-edit-vet.component.ts
> +	openDialog(row: IVetsUnitInfo) {
Access modifiers need to be added

2022-02-04 23:24 UTC, sanderpa commented on client/src/app/admin-page/components/admin-edit-vet/admin-edit-vet.component.ts
> +	onOpenAddDialog(): void {
Access modifiers need to be added

2022-02-04 23:24 UTC, sanderpa commented on client/src/app/admin-page/components/admin-edit-vet/admin-edit-vet.component.ts
> +	onOpenDeleteDialog(id: number): void {
Access modifiers need to be added

2022-02-04 23:24 UTC, sanderpa commented on client/src/app/admin-page/components/admin-edit-vet/admin-edit-vet.component.ts
> +	onDeleteClinic(id: number): void {
Access modifiers need to be added

2022-02-05 00:07 UTC, Samwa-ua commented on client/src/app/admin-page/components/admin-edit-vet/admin-edit-vet.component.html
> +            <th mat-header-cell *matHeaderCellDef>Адреса</th>
Not all columns need to be sorted

2022-02-05 00:15 UTC, Samwa-ua approved these changes

2022-02-05 00:15 UTC, Samwa-ua commented on client/src/app/admin-page/components/admin-edit-vet/admin-edit-vet.component.ts
> +	IVetsInfo$: Observable<Array<IVetsUnitInfo>>
Where did you use this observable ?

2022-02-05 00:15 UTC, Samwa-ua commented on client/src/app/admin-page/components/update-vet/update-vet.component.html
> +      <mat-label>No</mat-label>
ID?

2022-02-05 10:20 UTC, closed without merging